# Generated by Django 5.1.5 on 2025-05-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payment_ref_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='count',
            new_name='quantity',
        ),
    ]
